name: Publish NPM Package
on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - "package/**"
      - ".github/workflows/package.yaml"

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: npm install
      - name: authenticate
        run: echo '//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}' > ~/.npmrc
      - name: build
      # https://github.com/microsoft/TypeScript/issues/27379
        run: npx tsc package/**/*.ts package/**/*.tsx --jsx react-jsx --target es2019 --lib esnext,dom,dom.iterable --module commonjs --moduleResolution node --declaration --outDir dist --strict --esModuleInterop --noUnusedLocals --noUnusedParameters --noImplicitReturns --noImplicitThis --noImplicitAny --forceConsistentCasingInFileNames --allowSyntheticDefaultImports --skipLibCheck --isolatedModules --resolveJsonModule
      - name: prepare
        run: cp LICENSE README.md package.json package/declare.d.ts dist
      - name: publish
        run: npm publish --access public
        working-directory: package/dist
