name: Publish NPM Package
on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - "package/**"
      - ".github/workflows/package.yaml"

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: npm install
      - name: package
        run: node scripts/package.js
      - name: publish
        run: npm publish --access public
        working-directory: dist
