name: Publish samepage npm package
on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - "package/**"
      - ".github/workflows/package.yaml"

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: npm install
      - name: package deps
        run: npm install
        working-directory: package
      - name: authenticate
        run: echo '//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}' > ~/.npmrc
      - name: build
        run: npx tsc
        working-directory: package
      - name: prepare
        run: cp ../LICENSE README.md package.json dist
        working-directory: package
      - name: publish
        run: npm publish --access public
        working-directory: package/dist
