name: Run Full Tests Suite
on:
  pull_request:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - "tests/**"
      - ".github/workflows/tests.yaml"

env:
  API_URL: http://localhost:3003
  AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOY_AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOY_AWS_ACCESS_SECRET }}
  AWS_REGION: us-east-1
  CLERK_API_KEY: ${{ secrets.STAGING_CLERK_API_KEY }}
  CLERK_FRONTEND_API: clerk.in.horse-0.lcl.dev
  DATABASE_URL: mysql://root:root@localhost:3306/samepage_network
  ORIGIN: https://samepage.network
  WEB3_STORAGE_API_KEY: ${{ secrets.WEB3_STORAGE_API_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: install
        run: npm install
      - name: package deps
        run: |
          npm install
          rm -Rf node_modules/react node_modules/react-dom node_modules/jsdom
        working-directory: package
      - name: Install playwright
        run: npx playwright install
      - name: setup mysql
        run: |
          sudo systemctl start mysql.service
          mysql -e "CREATE DATABASE samepage_network" -uroot -proot
          npx fuego plan --sql
          npx fuego apply --sql
      - name: tests
        run: npm t
