name: Run Full Tests Suite
on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - "tests/**"
      - ".github/workflows/tests.yaml"
      
env:
  DATABASE_URL: mysql://root:root@localhost:3306/samepage_network

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: npm install
      - name: package deps
        run: | 
          npm install
          rm -Rf node_modules/react node_modules/react-dom
        working-directory: package
      - name: setup mysql
        run: |
          sudo systemctl start mysql.service
          mysql -e "CREATE DATABASE samepage_network" -uroot -proot
          npx fuego plan --sql
          npx fuego apply --sql
      - name: tests
        run: npm t
        env:
          DEBUG: true